version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-cont
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e-tron-db
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - etron-network

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-cont
    ports:
      - "8083:8083"
    networks:
      - etron-network
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-cont:3306/e-tron-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

networks:
  etron-network:
